### ISSUE TITLE
用摄像头发视频时，崩溃

### ISSUE THREAD

**Issue by china-coder** [jpush/aurora-imui#139]
### My environment: 
   native 7.0
华为Emtion ui5.0.1
测试机型有软键盘
消息提示录音失败
提示这个错误： java.lang.IllegalStateException: CameraDevice was already closed
完整的错误栈：
1.
   android.hardware.camera2.CameraAccessException: CAMERA_DISCONNECTED (2): cancelRequest:291: Camera device no longer alive
                                                             at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:633)
                                                             at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:95)
                                                             at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:926)
                                                             at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:379)
                                                             at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:515)
                                                             at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:228)
                                                             at android.os.Handler.handleCallback(Handler.java:761)
                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
                                                             at android.os.Looper.loop(Looper.java:156)
                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
                                                          Caused by: android.os.ServiceSpecificException: cancelRequest:291: Camera device no longer alive
                                                             at android.os.Parcel.readException(Parcel.java:1679)
                                                             at android.os.Parcel.readException(Parcel.java:1618)
                                                             at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:350)
                                                             at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:93)

2.
   at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:1988)
                                                       at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:857)
                                                       at android.hardware.camera2.impl.CameraDeviceImpl.setRepeatingRequest(CameraDeviceImpl.java:904)
                                                       at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:236)
                                                       at cn.jiguang.imui.chatinput.camera.CameraNew.updatePreview(CameraNew.java:461)
                                                       at cn.jiguang.imui.chatinput.camera.CameraNew.access$800(CameraNew.java:68)
                                                       at cn.jiguang.imui.chatinput.camera.CameraNew$4.onConfigured(CameraNew.java:380)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
                                                       at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
                                                       at android.os.Handler.handleCallback(Handler.java:761)
                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                       at android.os.Looper.loop(Looper.java:156)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by KenChoi1992** [comment]
@china-coder 这个日志看不到报错在哪一行，你看看能不能复现场景，截一下正确的日志。

**Comment by china-coder** [comment]
嗯嗯 是的，在拍照的时候，最小化窗口可以，但是最大化的情况下拍照，就会出现这个问题。

**Comment by KenChoi1992** [comment]
@china-coder 我自己测试是没有出现这个问题的。

**Comment by china-coder** [comment]
嗯嗯 我在我的魅族手机上测试也是没有问题，华为的手机上面好想普遍一点。

**Comment by KenChoi1992** [comment]
@china-coder 你可以试试把其他的应用关了，看看是不是有点应用打开了摄像头，然后测试一下。我用乐2 测试没问题，我再用华为测试一下。

**Comment by KenChoi1992** [comment]
@china-coder 我用华为 GRA-TL00 测试没有问题。你的是什么型号

**Comment by china-coder** [comment]
![image](https://user-images.githubusercontent.com/13534737/33118183-06761ff0-cfa6-11e7-89b2-be3198e88026.png)
设备型号是HUAWEI Mate8 和华为 note8 都出现崩溃问题

**Comment by KenChoi1992** [comment]
@china-coder 试试更新版本，应该修复了。

**Comment by china-coder** [comment]
好的

**Comment by laienliang** [comment]
遇到一样的问题，请问用哪个版本解决了呢?
