### ISSUE TITLE
android 使用报错，可否留个QQ群？

### ISSUE THREAD

**Issue by yzcheng90** [jpush/aurora-imui#174]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.ski.mobile.app.psm.sk_psm, PID: 5629
                  java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Enum.ordinal()' on a null object reference
                      at cn.jiguang.imui.messages.TxtViewHolder.onBind(TxtViewHolder.java:59)
                      at cn.jiguang.imui.messages.TxtViewHolder.onBind(TxtViewHolder.java:15)
                      at cn.jiguang.imui.messages.MsgListAdapter.onBindViewHolder(MsgListAdapter.java:256)
                      at cn.jiguang.imui.messages.MsgListAdapter.onBindViewHolder(MsgListAdapter.java:24)
                      at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                      at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                      at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                      at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                      at android.view.View.layout(View.java:17663)
                      at android.view.ViewGroup.layout(ViewGroup.java:5577)
                      at cn.jiguang.imui.messages.ptr.PullToRefreshLayout.onLayout(PullToRefreshLayout.java:144)
                      at android.view.View.layout(View.java:17663)
                      at android.view.ViewGroup.layout(ViewGroup.java:5577)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                      at android.view.View.layout(View.java:17663)
                      at android.view.ViewGroup.layout(ViewGroup.java:5577)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                      at android.view.View.layout(View.java:17663)
                      at android.view.ViewGroup.layout(ViewGroup.java:5577)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at android.view.View.layout(View.java:17663)
                      at android.view.ViewGroup.layout(ViewGroup.java:5577)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                      at android.view.View.layout(View.java:17663)
                      at android.view.ViewGroup.layout(ViewGroup.java:5577)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at android.view.View.layout(View.java:17663)
                      at android.view.ViewGroup.layout(ViewGroup.java:5577)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                      at android.view.View.layout(View.java:17663)
                      at android.view.ViewGroup.layout(ViewGroup.java:5577)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at com.android.internal.policy.DecorView.onLayout(DecorView.java:730)
                      at android.view.View.layout(View.java:17663)
                      at android.view.ViewGroup.layout(ViewGroup.java:5577)
E/AndroidRuntime:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2392)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2114)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1300)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6405)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:688)
                      at android.view.Choreographer.doFrame(Choreographer.java:623)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
                      at android.os.Handler.handleCallback(Handler.java:754)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:163)
                      at android.app.ActivityThread.main(ActivityThread.java:6274)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)

**Comment by huangminlinux** [comment]
QQ Group: 604798367
