### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by potian2017** [jpush/aurora-imui#221]
### My environment:

报错Didn't find class "android.support.v4.animation.AnimatorCompatHelper

 java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
                      at android.support.v7.widget.DefaultItemAnimator.resetAnimation(DefaultItemAnimator.java:515)
                      at android.support.v7.widget.DefaultItemAnimator.animateMove(DefaultItemAnimator.java:255)
                      at android.support.v7.widget.SimpleItemAnimator.animateDisappearance(SimpleItemAnimator.java:90)
                      at android.support.v7.widget.RecyclerView.animateDisappearance(RecyclerView.java:3813)
                      at android.support.v7.widget.RecyclerView$4.processDisappeared(RecyclerView.java:516)
                      at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:234)
                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3653)
                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3323)
                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                      at android.view.View.layout(View.java:17523)
                      at android.view.ViewGroup.layout(ViewGroup.java:5612)
                      at cn.jiguang.imui.messages.ptr.PullToRefreshLayout.onLayout(PullToRefreshLayout.java:144)!!!这里报错了

if (mMsgList != null) {
            MarginLayoutParams params = (MarginLayoutParams) mMsgList.getLayoutParams();
            int left = paddingLeft + params.leftMargin;
            int top = paddingTop + params.topMargin;
            int right = left + mMsgList.getMeasuredWidth();
            int bottom = top + mMsgList.getMeasuredHeight();
            mMsgList.layout(left, top, right, bottom);!!!定位到这行代码出错

**Comment by KenChoi1992** [comment]
@potian2017 你没安装 support v4 包
