### ISSUE TITLE
点击拍照菜单，放大后拍完照不能正确返回！

### ISSUE THREAD

**Issue by DevXue** [jpush/aurora-imui#226]
### Android 
  

我运行Demo，发现拍照模块，当我点击拍照，然后点击放大全屏，点击拍，他就定在那不动了一直处于全屏····而且也不显示我拍的结果···，不知道咋回事，我用小米Note  Android6.0   MUI8 测试的，另外有一台4.4的Android手机也是这情况，  烦请看看   谢谢！

![sasasasas](https://user-images.githubusercontent.com/9455329/34805056-d9e0ae78-f6b6-11e7-9558-f6090688bc0b.png)

**Comment by KenChoi1992** [comment]
@DevXue 贴一下日志

**Comment by DevXue** [comment]
@KenChoi1992 

01-11 10:11:42.043 7778-7778/imui.jiguang.cn.imuisample E/ChatInputView: Opening camera
01-11 10:11:42.045 7778-7778/imui.jiguang.cn.imuisample I/CameraManagerGlobal: Connecting to camera service
01-11 10:11:42.096 7778-7778/imui.jiguang.cn.imuisample I/CameraManager: Using legacy camera HAL.
01-11 10:11:42.290 7778-8394/imui.jiguang.cn.imuisample I/CameraDeviceState: Legacy camera service transitioning to state CONFIGURING
01-11 10:11:42.293 7778-8434/imui.jiguang.cn.imuisample I/RequestThread-0: Configure outputs: 2 surfaces configured.
01-11 10:11:42.293 7778-8434/imui.jiguang.cn.imuisample D/Camera: app passed NULL surface
01-11 10:11:42.296 7778-8434/imui.jiguang.cn.imuisample I/RequestThread-0: configureOutputs - set take picture size to 4160x3120
01-11 10:11:42.329 7778-8394/imui.jiguang.cn.imuisample I/CameraDeviceState: Legacy camera service transitioning to state IDLE
01-11 10:11:42.332 7778-8394/imui.jiguang.cn.imuisample I/RequestQueue: Repeating capture request set.
01-11 10:11:42.335 7778-8434/imui.jiguang.cn.imuisample W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
01-11 10:11:42.335 7778-8434/imui.jiguang.cn.imuisample W/LegacyRequestMapper: Only received metering rectangles with weight 0.
01-11 10:11:42.335 7778-8434/imui.jiguang.cn.imuisample W/LegacyRequestMapper: Only received metering rectangles with weight 0.
01-11 10:11:42.678 7778-8435/imui.jiguang.cn.imuisample I/CameraDeviceState: Legacy camera service transitioning to state CAPTURING
01-11 10:11:47.038 7778-7778/imui.jiguang.cn.imuisample E/ChatInputView: Texture size changed, Opening camera
01-11 10:11:47.062 7778-7778/imui.jiguang.cn.imuisample I/CameraManager: Using legacy camera HAL.
01-11 10:11:47.076 7778-8395/imui.jiguang.cn.imuisample E/Camera: Error 2
01-11 10:11:47.076 7778-8395/imui.jiguang.cn.imuisample I/RequestThread-0: Flushing all pending requests.
01-11 10:11:47.076 7778-8395/imui.jiguang.cn.imuisample I/RequestQueue: Repeating capture request cancelled.
01-11 10:11:47.076 7778-8395/imui.jiguang.cn.imuisample W/RequestHolder: Capture failed for request: 0
01-11 10:11:47.076 7778-8395/imui.jiguang.cn.imuisample I/CameraDeviceState: Legacy camera service transitioning to state ERROR
01-11 10:11:47.079 7778-8394/imui.jiguang.cn.imuisample E/RequestQueue: cancel failed: no repeating request exists for request id: 0
01-11 10:11:47.188 7778-7791/imui.jiguang.cn.imuisample E/BufferQueueProducer: [SurfaceTexture-1-7778-1] cancelBuffer: BufferQueue has been abandoned
01-11 10:11:47.189 7778-7792/imui.jiguang.cn.imuisample E/BufferQueueProducer: [SurfaceTexture-1-7778-1] cancelBuffer: BufferQueue has been abandoned
01-11 10:11:47.189 7778-7856/imui.jiguang.cn.imuisample E/BufferQueueProducer: [SurfaceTexture-1-7778-1] cancelBuffer: BufferQueue has been abandoned
01-11 10:11:47.190 7778-7791/imui.jiguang.cn.imuisample E/BufferQueueProducer: [SurfaceTexture-1-7778-1] cancelBuffer: BufferQueue has been abandoned
01-11 10:11:47.190 7778-7792/imui.jiguang.cn.imuisample E/BufferQueueProducer: [SurfaceTexture-1-7778-1] cancelBuffer: BufferQueue has been abandoned
01-11 10:11:47.242 7778-8434/imui.jiguang.cn.imuisample W/RequestThread-0: Jpeg surface is invalid, skipping...
01-11 10:11:47.404 7778-8492/imui.jiguang.cn.imuisample I/CameraDeviceState: Legacy camera service transitioning to state CONFIGURING
01-11 10:11:47.405 7778-8534/imui.jiguang.cn.imuisample I/RequestThread-0: Configure outputs: 2 surfaces configured.
01-11 10:11:47.405 7778-8534/imui.jiguang.cn.imuisample D/Camera: app passed NULL surface
01-11 10:11:47.411 7778-8534/imui.jiguang.cn.imuisample I/RequestThread-0: configureOutputs - set take picture size to 4160x3120
01-11 10:11:47.429 7778-8492/imui.jiguang.cn.imuisample I/CameraDeviceState: Legacy camera service transitioning to state IDLE
01-11 10:11:47.431 7778-8492/imui.jiguang.cn.imuisample I/RequestQueue: Repeating capture request set.
01-11 10:11:47.433 7778-8534/imui.jiguang.cn.imuisample W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
01-11 10:11:47.434 7778-8534/imui.jiguang.cn.imuisample W/LegacyRequestMapper: Only received metering rectangles with weight 0.
01-11 10:11:47.434 7778-8534/imui.jiguang.cn.imuisample W/LegacyRequestMapper: Only received metering rectangles with weight 0.
01-11 10:11:47.799 7778-8535/imui.jiguang.cn.imuisample I/CameraDeviceState: Legacy camera service transitioning to state CAPTURING
01-11 10:11:49.847 7778-8534/imui.jiguang.cn.imuisample W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
01-11 10:11:49.847 7778-8534/imui.jiguang.cn.imuisample W/LegacyRequestMapper: Only received metering rectangles with weight 0.
01-11 10:11:49.847 7778-8534/imui.jiguang.cn.imuisample W/LegacyRequestMapper: Only received metering rectangles with weight 0.
01-11 10:11:49.890 7778-8493/imui.jiguang.cn.imuisample D/LegacyFocusStateMapper: onAutoFocusMoving - ignoring move callbacks from old af run1
01-11 10:11:49.936 7778-8492/imui.jiguang.cn.imuisample I/RequestQueue: Repeating capture request cancelled.
01-11 10:11:49.939 7778-8534/imui.jiguang.cn.imuisample W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
01-11 10:11:49.939 7778-8534/imui.jiguang.cn.imuisample W/LegacyRequestMapper: Only received metering rectangles with weight 0.
01-11 10:11:49.939 7778-8534/imui.jiguang.cn.imuisample W/LegacyRequestMapper: Only received metering rectangles with weight 0.
01-11 10:11:50.014 7778-8534/imui.jiguang.cn.imuisample W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
01-11 10:11:50.014 7778-8534/imui.jiguang.cn.imuisample W/LegacyRequestMapper: Only received metering rectangles with weight 0.
01-11 10:11:50.014 7778-8534/imui.jiguang.cn.imuisample W/LegacyRequestMapper: Only received metering rectangles with weight 0.
01-11 10:11:50.785 7778-8493/imui.jiguang.cn.imuisample I/RequestThread-0: Received jpeg.
01-11 10:11:50.785 7778-8493/imui.jiguang.cn.imuisample I/RequestThread-0: Producing jpeg buffer...
01-11 10:11:50.791 7778-8492/imui.jiguang.cn.imuisample D/ImageReader_JNI: ImageReader_lockedImageSetup: Receiving JPEG in HAL_PIXEL_FORMAT_RGBA_8888 buffer.
01-11 10:11:50.819 7778-8534/imui.jiguang.cn.imuisample I/CameraDeviceState: Legacy camera service transitioning to state IDLE
01-11 10:11:50.821 7778-8492/imui.jiguang.cn.imuisample I/RequestQueue: Repeating capture request set.
01-11 10:11:50.826 7778-8534/imui.jiguang.cn.imuisample W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
01-11 10:11:50.826 7778-8534/imui.jiguang.cn.imuisample W/LegacyRequestMapper: Only received metering rectangles with weight 0.
01-11 10:11:50.826 7778-8534/imui.jiguang.cn.imuisample W/LegacyRequestMapper: Only received metering rectangles with weight 0.
01-11 10:11:50.850 7778-7778/imui.jiguang.cn.imuisample E/ChatInputView: Texture size changed, Opening camera
01-11 10:11:50.887 7778-7778/imui.jiguang.cn.imuisample I/CameraManager: Using legacy camera HAL.
01-11 10:11:50.889 7778-8493/imui.jiguang.cn.imuisample E/Camera: Error 2
01-11 10:11:50.889 7778-8493/imui.jiguang.cn.imuisample I/RequestThread-0: Flushing all pending requests.
01-11 10:11:50.889 7778-8493/imui.jiguang.cn.imuisample I/RequestQueue: Repeating capture request cancelled.
01-11 10:11:50.889 7778-8493/imui.jiguang.cn.imuisample W/RequestHolder: Capture failed for request: 3
01-11 10:11:50.889 7778-8493/imui.jiguang.cn.imuisample I/CameraDeviceState: Legacy camera service transitioning to state CAPTURING
01-11 10:11:50.890 7778-8493/imui.jiguang.cn.imuisample I/CameraDeviceState: Legacy camera service transitioning to state ERROR
01-11 10:11:50.891 7778-8492/imui.jiguang.cn.imuisample E/RequestQueue: cancel failed: no repeating request exists for request id: 4
01-11 10:11:51.125 7778-8534/imui.jiguang.cn.imuisample E/RequestThread-0: Received device exception during capture call: 
                                                                           java.lang.RuntimeException: enable focus move callback failed
                                                                               at android.hardware.Camera.enableFocusMoveCallback(Native Method)
                                                                               at android.hardware.Camera.setAutoFocusMoveCallback(Camera.java:1397)
                                                                               at android.hardware.camera2.legacy.LegacyFocusStateMapper.processRequestTriggers(LegacyFocusStateMapper.java:165)
                                                                               at android.hardware.camera2.legacy.RequestThreadManager$5.handleMessage(RequestThreadManager.java:824)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
01-11 10:11:51.326 7778-8603/imui.jiguang.cn.imuisample I/CameraDeviceState: Legacy camera service transitioning to state CONFIGURING
01-11 10:11:51.326 7778-8657/imui.jiguang.cn.imuisample I/RequestThread-0: Configure outputs: 2 surfaces configured.
01-11 10:11:51.326 7778-8657/imui.jiguang.cn.imuisample D/Camera: app passed NULL surface
01-11 10:11:51.329 7778-8657/imui.jiguang.cn.imuisample I/RequestThread-0: configureOutputs - set take picture size to 4160x3120
01-11 10:11:51.346 7778-8603/imui.jiguang.cn.imuisample I/CameraDeviceState: Legacy camera service transitioning to state IDLE
01-11 10:11:51.347 7778-8603/imui.jiguang.cn.imuisample I/RequestQueue: Repeating capture request set.
01-11 10:11:51.349 7778-8657/imui.jiguang.cn.imuisample W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
01-11 10:11:51.349 7778-8657/imui.jiguang.cn.imuisample W/LegacyRequestMapper: Only received metering rectangles with weight 0.
01-11 10:11:51.350 7778-8657/imui.jiguang.cn.imuisample W/LegacyRequestMapper: Only received metering rectangles with weight 0.
01-11 10:11:51.696 7778-8658/imui.jiguang.cn.imuisample I/CameraDeviceState: Legacy camera service transitioning to state CAPTURING

**Comment by DevXue** [comment]
![sasasasasasasa](https://user-images.githubusercontent.com/9455329/34805266-17bfc930-f6b8-11e7-85aa-e0c05a5a2bbe.png)
看到了两处异常！  @KenChoi1992

**Comment by KenChoi1992** [comment]
@DevXue 这确实是个 bug，等下发个版本修复。

**Comment by DevXue** [comment]
@KenChoi1992   谢谢，这个应该是chatInput模块中的Bug吧？
