### ISSUE TITLE
相机问题

### ISSUE THREAD

**Issue by duan997625280** [jpush/aurora-imui#28]
相机在vivo x_shot 手机上 出现点击相机直接程序退出运行
FATAL EXCEPTION: main
                                                                                Process: imui.jiguang.cn.imuisample.dev, PID: 19357
                                                                                java.lang.ClassCastException: android.widget.RelativeLayout$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams
                                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:311)
                                                                                    at android.view.View.measure(View.java:16552)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5130)
                                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                    at android.view.View.measure(View.java:16552)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5130)
                                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                                    at android.view.View.measure(View.java:16552)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5130)
                                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                                    at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1052)
                                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:590)
                                                                                    at android.view.View.measure(View.java:16552)
                                                                                    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
                                                                                    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
                                                                                    at android.view.View.measure(View.java:16552)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5130)
                                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                    at android.view.View.measure(View.java:16552)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5130)
                                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                                    at android.view.View.measure(View.java:16552)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5130)
                                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2338)
                                                                                    at android.view.View.measure(View.java:16552)
                                                                                    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1965)
                                                                                    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1132)
                                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1314)
                                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1019)
                                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5743)
                                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
                                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:596)
                                                                                    at android.view.Choreographer.doFrame(Choreographer.java:565)
                                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
                                                                                    at android.os.Handler.handleCallback(Handler.java:733)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:136)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596)
                                                                                    at dalvik.system.NativeStart.main(Native Method)

 在oppo R9sk 上面出现相机切换为前置摄像头直接卡死  
05-17 14:00:15.339 12922-12933/imui.jiguang.cn.imuisample.dev E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                            java.lang.Throwable: Explicit termination method 'release' not called
                                                                                at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                                at android.view.Surface.setNativeObjectLocked(Surface.java:459)
                                                                                at android.view.Surface.<init>(Surface.java:145)
                                                                                at cn.jiguang.imui.chatinput.camera.CameraNew.createCameraPreview(CameraNew.java:179)
                                                                                at cn.jiguang.imui.chatinput.camera.CameraNew$6.onCaptureCompleted(CameraNew.java:364)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
                                                                                at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:179)
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by KenChoi1992** [comment]
@duan997625280 第一个问题没看出来是哪一行报错了。第二个问题应该是个 bug，没有释放 surface。下个版本修复。

**Comment by duan997625280** [comment]
@KenChoi1992 恩 目前我在使用aurora ui第一版本采用了系统相机去实现 希望能在我做第二版前你们也能修复这个问题

**Comment by duan997625280** [comment]
@KenChoi1992 还有一个就是我公司目前android这边已经完成了imui功能但是ios采用的oc去完成的 他们对swift不熟 你们这边有oc版本的aurora-imui吗

**Comment by huangminlinux** [comment]
后面会出一个 OC 使用 这个库的 Demo
