### ISSUE TITLE
java.io.NotSerializableException: cn.jpush.im.android.b.e 

### ISSUE THREAD

**Issue by SoyaLeaf** [jpush/aurora-imui#300]
### My environment:

Android 8.0 
``` 
   compile 'cn.jiguang.sdk:jmessage:2.5.0'  // 此处以JMessage 2.5.0 版本为例。
    compile 'cn.jiguang.sdk:jcore:1.1.9'  // 此处以JCore 1.1.9 版本为例。
    compile 'cn.jiguang.imui:chatinput:0.6.5'
    compile 'cn.jiguang.imui:messagelist:0.6.4'
```
```
Caused by: java.io.NotSerializableException: cn.jpush.im.android.b.e
                                                                           at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1233)
                                                                           at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1597)
                                                                           at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1558)
                                                                           at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1481)
                                                                           at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1227)
                                                                           at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
                                                                           at android.os.Parcel.writeSerializable(Parcel.java:1756)
                                                                           at android.os.Parcel.writeValue(Parcel.java:1709) 
                                                                           at android.os.Parcel.writeArrayMapInternal(Parcel.java:777) 
                                                                           at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1506) 
                                                                           at android.os.Bundle.writeToParcel(Bundle.java:1181) 
                                                                           at android.os.Parcel.writeBundle(Parcel.java:817) 
                                                                           at android.support.v4.app.FragmentState.writeToParcel(FragmentState.java:123) 
                                                                           at android.os.Parcel.writeTypedArray(Parcel.java:1401) 
                                                                           at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:619) 
                                                                           at android.os.Parcel.writeParcelable(Parcel.java:1730) 
                                                                           at android.os.Parcel.writeValue(Parcel.java:1636) 
                                                                           at android.os.Parcel.writeArrayMapInternal(Parcel.java:777) 
                                                                           at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1506) 
                                                                           at android.os.Bundle.writeToParcel(Bundle.java:1181) 
                                                                           at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4686) 
                                                                           at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3998) 
                                                                           at android.os.Handler.handleCallback(Handler.java:789) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                           at android.os.Looper.loop(Looper.java:164) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6548) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by KenChoi1992** [comment]
你这个不是 IMUI 的问题。
