### ISSUE TITLE
android按照文档加入项目报错

### ISSUE THREAD

**Issue by 1smartone1** [jpush/aurora-imui#359]
麻烦了～

Attempt to invoke virtual method 'int android.util.SparseArray.size()' on a null object referencejava.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.SparseArray.size()' on a null object reference
                                                                                                                  	at cn.jiguang.imui.messages.MsgListAdapter.getCustomType(MsgListAdapter.java:213) ~[na:0.0]
                                                                                                                  	at cn.jiguang.imui.messages.MsgListAdapter.getItemViewType(MsgListAdapter.java:206) ~[na:0.0]
                                                                                                                  	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5820) ~[na:0.0]
                                                                                                                  	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752) ~[na:0.0]
                                                                                                                  	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748) ~[na:0.0]
                                                                                                                  	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232) ~[na:0.0]
                                                                                                                  	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559) ~[na:0.0]
                                                                                                                  	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519) ~[na:0.0]
                                                                                                                  	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614) ~[na:0.0]
                                                                                                                  	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812) ~[na:0.0]
                                                                                                                  	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529) ~[na:0.0]
                                                                                                                  	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082) ~[na:0.0]
                                                                                                                  	at android.view.View.layout(View.java:18799) ~[na:0.0]
                                                                                                                  	at android.view.ViewGroup.layout(ViewGroup.java:5952) ~[na:0.0]
                                                                                                                  	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079) ~[na:0.0]
                                                                                                                  	at android.view.View.layout(View.java:18799) ~[na:0.0]
                                                                                                                  	at android.view.ViewGroup.layout(ViewGroup.java:5952) ~[na:0.0]
                                                                                                                  	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) ~[na:0.0]
                                                                                                                  	at android.widget.FrameLayout.onLayout(FrameLayout.java:261) ~[na:0.0]
                                                                                                                  	at android.view.View.layout(View.java:18799) ~[na:0.0]
                                                                                                                  	at android.view.ViewGroup.layout(ViewGroup.java:5952) ~[na:0.0]
                                                                                                                  	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741) ~[na:0.0]
                                                                                                                  	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585) ~[na:0.0]
                                                                                                                  	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494) ~[na:0.0]
                                                                                                                  	at android.view.View.layout(View.java:18799) ~[na:0.0]
                                                                                                                  	at android.view.ViewGroup.layout(ViewGroup.java:5952) ~[na:0.0]
                                                                                                                  	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) ~[na:0.0]
                                                                                                                  	at android.widget.FrameLayout.onLayout(FrameLayout.java:261) ~[na:0.0]
                                                                                                                  	at android.view.View.layout(View.java:18799) ~[na:0.0]
                                                                                                                  	at android.view.ViewGroup.layout(ViewGroup.java:5952) ~[na:0.0]
                                                                                                                  	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741) ~[na:0.0]
                                                                                                                  	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585) ~[na:0.0]
                                                                                                                  	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494) ~[na:0.0]
                                                                                                                  	at android.view.View.layout(View.java:18799) ~[na:0.0]
                                                                                                                  	at android.view.ViewGroup.layout(ViewGroup.java:5952) ~[na:0.0]
                                                                                                                  	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) ~[na:0.0]
                                                                                                                  	at android.widget.FrameLayout.onLayout(FrameLayout.java:261) ~[na:0.0]
                                                                                                                  	at com.android.internal.policy.DecorView.onLayout(DecorView.java:822) ~[na:0.0]
                                                                                                                  	at android.view.View.layout(View.java:18799) ~[na:0.0]
                                                                                                                  	at android.view.ViewGroup.layout(ViewGroup.java:5952) ~[na:0.0]
                                                                                                                  	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2627) ~[na:0.0]
                                                                                                                  	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2343) ~[na:0.0]
                                                                                                                  	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1502) ~[na:0.0]
                                                                                                                  	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7044) ~[na:0.0]
                                                                                                                  	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927) ~[na:0.0]
                                                                                                                  	at android.view.Choreographer.doCallbacks(Choreographer.java:702) ~[na:0.0]
                                                                                                                  	at android.view.Choreographer.doFrame(Choreographer.java:638) ~[na:0.0]
                                                                                                                  	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer

**Comment by 1smartone1** [comment]
能告诉下是哪里配置不对么？

**Comment by JoshLipan** [comment]
重复，关闭，见[#363](https://github.com/jpush/aurora-imui/issues/363)
