### ISSUE TITLE
按照文档加入报错 麻烦给看下 急 谢谢！！！

### ISSUE THREAD

**Issue by 1smartone1** [jpush/aurora-imui#363]
Attempt to invoke virtual method 'int android.util.SparseArray.size()' on a null object referencejava.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.SparseArray.size()' on a null object reference
at cn.jiguang.imui.messages.MsgListAdapter.getCustomType(MsgListAdapter.java:213) ~[na:0.0]
at cn.jiguang.imui.messages.MsgListAdapter.getItemViewType(MsgListAdapter.java:206) ~[na:0.0]
at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5820) ~[na:0.0]
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752) ~[na:0.0]
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748) ~[na:0.0]
at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232) ~[na:0.0]
at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559) ~[na:0.0]
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519) ~[na:0.0]
at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614) ~[na:0.0]
at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812) ~[na:0.0]
at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529) ~[na:0.0]
at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082) ~[na:0.0]
at android.view.View.layout(View.java:18799) ~[na:0.0]
at android.view.ViewGroup.layout(ViewGroup.java:5952) ~[na:0.0]
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079) ~[na:0.0]
at android.view.View.layout(View.java:18799) ~[na:0.0]
at android.view.ViewGroup.layout(ViewGroup.java:5952) ~[na:0.0]
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) ~[na:0.0]
at android.widget.FrameLayout.onLayout(FrameLayout.java:261) ~[na:0.0]
at android.view.View.layout(View.java:18799) ~[na:0.0]
at android.view.ViewGroup.layout(ViewGroup.java:5952) ~[na:0.0]
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741) ~[na:0.0]
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585) ~[na:0.0]
at android.widget.LinearLayout.onLayout(LinearLayout.java:1494) ~[na:0.0]
at android.view.View.layout(View.java:18799) ~[na:0.0]
at android.view.ViewGroup.layout(ViewGroup.java:5952) ~[na:0.0]
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) ~[na:0.0]
at android.widget.FrameLayout.onLayout(FrameLayout.java:261) ~[na:0.0]
at android.view.View.layout(View.java:18799) ~[na:0.0]
at android.view.ViewGroup.layout(ViewGroup.java:5952) ~[na:0.0]
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741) ~[na:0.0]
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585) ~[na:0.0]
at android.widget.LinearLayout.onLayout(LinearLayout.java:1494) ~[na:0.0]
at android.view.View.layout(View.java:18799) ~[na:0.0]
at android.view.ViewGroup.layout(ViewGroup.java:5952) ~[na:0.0]
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) ~[na:0.0]
at android.widget.FrameLayout.onLayout(FrameLayout.java:261) ~[na:0.0]
at com.android.internal.policy.DecorView.onLayout(DecorView.java:822) ~[na:0.0]
at android.view.View.layout(View.java:18799) ~[na:0.0]
at android.view.ViewGroup.layout(ViewGroup.java:5952) ~[na:0.0]
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2627) ~[na:0.0]
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2343) ~[na:0.0]
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1502) ~[na:0.0]
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7044) ~[na:0.0]
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927) ~[na:0.0]
at android.view.Choreographer.doCallbacks(Choreographer.java:702) ~[na:0.0]
at android.view.Choreographer.doFrame(Choreographer.java:638) ~[na:0.0]
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer

**Comment by JoshLipan** [comment]
看错误是获取自定义消息类型失败，你是否调用了[addCustomMsgType](https://github.com/jpush/aurora-imui/blob/973f664b0376126b631e04bcb275ce7d842212ea/Android/messagelist/src/main/java/cn/jiguang/imui/messages/MsgListAdapter.java#L167)增加了自定义消息类型参数

**Comment by 1smartone1** [comment]
嗯嗯 掉了 CustomMsgConfig config1 = new CustomMsgConfig(13, R.layout.im_talk_sender_item, true, MyImTextViewHolder.class);
        adapter.addCustomMsgType(13, config1);

        CustomMsgConfig config2 = new CustomMsgConfig(14, R.layout.im_talk_receiver_item, true, MyImTextViewHolder.class);
        adapter.addCustomMsgType(14, config2);

**Comment by JoshLipan** [comment]
调用addCustomMsgType后还有问题没

**Comment by 1smartone1** [comment]
麻烦下 在线等 急！！！

**Comment by JoshLipan** [comment]
你在调用addToStart之前调用下[getCustomMsgList](https://github.com/jpush/aurora-imui/blob/973f664b0376126b631e04bcb275ce7d842212ea/Android/messagelist/src/main/java/cn/jiguang/imui/messages/MsgListAdapter.java#L174)看能拿到你设置的自定义消息配置吗

**Comment by 1smartone1** [comment]
可以
我的设置：
CustomMsgConfig config1 = new CustomMsgConfig(13, R.layout.im_talk_sender_item, true, MyImTextViewHolder.class);
        adapter.addCustomMsgType(13, config1);

        CustomMsgConfig config2 = new CustomMsgConfig(14, R.layout.im_talk_receiver_item, true, MyImTextViewHolder.class);
        adapter.addCustomMsgType(14, config2);

输出结果：
{13=cn.jiguang.imui.messages.CustomMsgConfig@994f8d3, 14=cn.jiguang.imui.messages.CustomMsgConfig@e706c10}

**Comment by JoshLipan** [comment]
看你的代码片段没看出什么问题，但你提供的log最后获取到的配置的list是null，建议你断点调试下看哪个地方又置为null了。<img width="659" alt="default" src="https://user-images.githubusercontent.com/16323137/39907607-51f1f73c-551c-11e8-91a6-167aaef4c44c.png">

**Comment by 1smartone1** [comment]
Ok 问题 解决了
