### ISSUE TITLE
RN Android录音失败

### ISSUE THREAD

**Issue by django-wong** [jpush/aurora-imui#423]
### My environment:
- `react-native` version: 0.54.4
- `aurora-imui-react-native` version: 试了 0.10.1、0.10.9、0.10.8
- `Platform`: Android

### 问题：
录音失败，m4a文件创建成功但是prepare失败
```
root@generic_x86_64:/data/user/0/cn.noviio.app/files/voice # ls -la
ls -la
-rw------- u0_a61   u0_a61       3225 2018-08-15 13:41 2018_0815_014145.m4a
-rw------- u0_a61   u0_a61       3225 2018-08-15 13:42 2018_0815_014213.m4a
-rw------- u0_a61   u0_a61       3225 2018-08-15 13:58 2018_0815_015845.m4a
-rw------- u0_a61   u0_a61       3225 2018-08-15 14:02 2018_0815_020225.m4a
```
### Log:
```
08-15 15:34:42.697 12031-12031/cn.noviio.app I/RecordVoiceButton: Create file success file path: /data/user/0/cn.noviio.app/files/voice/2018_0815_033442.m4a
08-15 15:34:42.697 12031-12031/cn.noviio.app E/ChatInputView: starting chronometer
08-15 15:34:42.713 12031-12031/cn.noviio.app I/RecordVoiceController: recorder prepare failed!
08-15 15:34:46.763 12031-12031/cn.noviio.app E/MediaRecorder: stop failed: -1007
08-15 15:34:46.763 12031-12031/cn.noviio.app D/RecordVoice: Catch exception: stop recorder failed!
08-15 15:34:46.770 12031-12043/cn.noviio.app E/MediaPlayer: error (1, -2147483648)
08-15 15:34:46.771 12031-12031/cn.noviio.app W/System.err: java.io.IOException: Prepare failed.: status=0x1
        at android.media.MediaPlayer._prepare(Native Method)
        at android.media.MediaPlayer.prepare(MediaPlayer.java:1163)
        at cn.jiguang.imui.chatinput.record.RecordVoiceButton.finishRecord(RecordVoiceButton.java:224)
        at cn.jiguang.imui.chatinput.record.RecordControllerView.onActionUp(RecordControllerView.java:198)
        at cn.jiguang.imui.chatinput.record.RecordVoiceButton.onTouchEvent(RecordVoiceButton.java:169)
        at android.view.View.dispatchTouchEvent(View.java:9294)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2765)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
        at android.view.View.dispatchPointerEvent(View.java:9514)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-15 15:34:46.771 12031-12031/cn.noviio.app E/MediaPlayer: Attempt to call getDuration without a valid mediaplayer
    error (-38, 0)
08-15 15:34:46.773 12031-12031/cn.noviio.app E/MediaPlayer: Error (-38,0)
08-15 15:34:46.775 12031-12064/cn.noviio.app D/AuroraIMUIModule: configure message: { NativeMap: {"mediaPath":"/data/user/0/cn.noviio.app/files/voice/2018_0815_033442.m4a","msgType":"voice","duration":1,"timeString":"safsdfa","fromUser":{"avatarPath":"","displayName":"","userId":null},"isOutgoing":true,"status":"send_going","msgId":"3"} }
    fromUser: {"displayName":"","avatarPath":""}
08-15 15:34:46.778 12031-12031/cn.noviio.app D/RCTMessageListManager: Add message to start, message: {"msgId":"3","status":"send_going","msgType":"voice","isOutgoing":true,"timeString":"safsdfa","mediaPath":"/data/user/0/cn.noviio.app/files/voice/2018_0815_033442.m4a","duration":1,"fromUser":{"displayName":"","avatarPath":""}}
08-15 15:34:57.691 12031-12039/cn.noviio.app W/MediaPlayer-JNI: MediaPlayer finalized without being released

```

**Comment by django-wong** [comment]
http://blog.weston-fl.com/android-mediaplayer-prepare-throws-status0x1-error1-2147483648/

**Comment by JoshLipan** [comment]
录音权限给了吗

**Comment by django-wong** [comment]
@JoshLipan 给了

```xml
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

**Comment by django-wong** [comment]
预览的时候提示文件不存在（但是文件确实创建成功了），所以我猜测是跟文件权限有关

**Comment by JoshLipan** [comment]
你测试出现问题的Android版本和机型是？

**Comment by django-wong** [comment]
锤子T1，Android 4.4.2，Smartisan 3.7.2

**Comment by JoshLipan** [comment]
已修复，更新版本到v0.10.11
