### ISSUE TITLE
设置视频录制按钮不可见经过全屏之后会失效

### ISSUE THREAD

**Issue by dogbutcat** [jpush/aurora-imui#426]
### My environment:
- `react-native` version: 0.51.0
- `aurora-imui-react-native` version: 0.10.10

- `Platform`: android 6.0.0 on HUAWEI P8 Max

### Description
设置属性showRecordVideoBtn(Android Only)之后 是可以屏蔽录制视频按钮 但经过全屏之后 好像就失效了 是否是相机控件崩溃引起

### Log
logcat中较有参考价值的错误
```
08-17 07:18:57.906 20429-21120/? E/HwParametersEx: Error finding static metadata entry 'android.huawei.device.capabilities.hdr_movie_supported' (80000010)
08-17 07:18:57.906 20429-21120/? E/HwParametersEx: Error finding static metadata entry 'android.huawei.device.capabilities.capture_mirror_supported' (80000011)
08-17 07:18:57.906 20429-21120/? E/HwParametersEx: Error finding static metadata entry 'android.huawei.device.capabilities.dual_primary_supported' (80000016)
08-17 07:18:57.906 20429-21120/? E/HwParametersEx: Error finding static metadata entry 'android.huawei.device.capabilities.super_resolution_supported' (8000001e)
08-17 07:18:57.906 20429-21120/? E/HwParametersEx: Error finding static metadata entry 'android.huawei.device.capabilities.hw_big_aperture_supported' (80000020)
08-17 07:18:57.907 20429-21120/? E/HwParametersEx: Error finding static metadata entry 'android.huawei.device.capabilities.hw_supported_aperture_value' (80000021)
08-17 07:18:57.907 20429-21120/? E/HwParametersEx: Error finding static metadata entry 'android.huawei.device.capabilities.hw_nice_food_supported' (80000024)
08-17 07:18:57.907 20429-21120/? E/HwParametersEx: Error finding static metadata entry 'android.huawei.device.capabilities.hw-video-fps-supported' (80000001)
08-17 07:18:57.907 20429-21120/? E/HwParametersEx: Error finding static metadata entry 'android.huawei.device.capabilities.front_flash_adjust_supported' (80000002)
08-17 07:18:57.907 20429-21120/? E/HwParametersEx: Error finding static metadata entry 'android.huawei.device.capabilities.hw_color_effect_range' (80000042)
08-17 07:18:57.907 20429-21120/? E/Camera2-Parameters: Error finding static metadata entry 'android.scaler.availableJpegMinDurations' (d0002)
···
08-17 07:19:00.210 20429-11392/? E/Camera2-FrameProcessor: get3aResult: Camera 0: No afMode provided by HAL for frame 24!
    get3aResult: Camera 0: No awbMode provided by HAL for frame 24!
    get3aResult: Camera 0: No aeState provided by HAL for frame 24!
    get3aResult: Camera 0: No afState provided by HAL for frame 24!
    get3aResult: Camera 0: No awbState provided by HAL for frame 24!
    get3aResult: Camera 0: No afTriggerId provided by HAL for frame 24!
    get3aResult: Camera 0: No aePrecaptureId provided by HAL for frame 24!
···
08-17 07:19:00.210 20429-11392/? E/CameraHwCallBack: android::status_t android::camera2::CameraHwCallBack::processOtpcheckResult(const CameraMetadata&) entry count error
    processDualAbnormal() invalid count = 0 
08-17 07:19:00.308 2963-3477/? E/ImagingSystem: COMMAND_FINISHED, cmdid[5]
08-17 07:19:00.308 2963-3477/? E/ImagingSystem: void hw::COVISP23IntrManager::DisableIntr(irq_type_e), unpair IRQ
08-17 07:19:00.346 2963-3477/? E/ImagingSystem: COMMAND_FINISHED, cmdid[2]
08-17 07:19:00.399 20429-21120/? E/camera_metadata: set_camera_metadata_vendor_tag_ops: This function has been deprecated
08-17 07:19:00.405 20429-20644/? E/CameraService: disconnect: Disconnect called on already disconnected client for device 0
08-17 07:19:00.405 20429-20644/? E/CameraService: disconnect: Disconnect called on already disconnected client for device 0
08-17 07:19:00.407 20747-21333/? E/HsmCoreServiceImpl: onTransact in code is: 102
```

### Reproduce
![cap](https://user-images.githubusercontent.com/8625449/44250480-57d63080-a1a9-11e8-8877-ac4bb6349946.gif)

**Comment by dogbutcat** [comment]
### Info Update

#### Relative Device

**Samsung Note 8(SN9500)** android _8.0.0_
**XiaoMi 8** android _8.1.0_
**HUAWEI P8 Max** android _6.0_

#### Description

* 在note8上直接点击拍照会触发三次拍照事件（怀疑和三星的双摄像头有关但试了小米8的双摄没问题）偶尔出现如下崩溃（note 8）。
``` logcat
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.camera2.CameraCaptureSession.capture(android.hardware.camera2.CaptureRequest, android.hardware.camera2.CameraCaptureSession$CaptureCallback, android.os.Handler)' on a null object reference
                      at cn.jiguang.imui.chatinput.camera.CameraNew.unlockFocus(CameraNew.java:745)
                      at cn.jiguang.imui.chatinput.camera.CameraNew.access$1100(CameraNew.java:66)
                      at cn.jiguang.imui.chatinput.camera.CameraNew$6.onCaptureCompleted(CameraNew.java:724)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
                      at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
                      at android.os.Handler.handleCallback(Handler.java:789)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.os.HandlerThread.run(HandlerThread.java:65)
```

* 竖着拍出来的照片显示是横向的（小米8和note8存在问题，华为P8没问题），但摄像的视频方向没有问题

**Comment by JoshLipan** [comment]
确实有这两个问题，下个版本修复

**Comment by JoshLipan** [comment]
已修复，更新版本到v0.10.11

**Comment by dogbutcat** [comment]
谢谢更新！由于进度比较急 而且的确相机的问题有点多…… 暂时以隐藏相机按钮处理 之后还有问题再来反馈

**Comment by cnpmge** [comment]
这个有录制视频的按钮吗，我打开相机点击按钮就是拍照功能，没有录制视频啊
