### ISSUE TITLE
Android 获取权限成功后，第一次拍照崩溃

### ISSUE THREAD

**Issue by junchenChow** [jpush/aurora-imui#435]
### My environment: android 7.0

`Process: imui.jiguang.cn.imuisample.dev, PID: 19072
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CaptureRequest$Builder.set(android.hardware.camera2.CaptureRequest$Key, java.lang.Object)' on a null object reference
        at cn.jiguang.imui.chatinput.camera.CameraNew.lockFocus(CameraNew.java:664)
        at cn.jiguang.imui.chatinput.camera.CameraNew.takePicture(CameraNew.java:655)
        at cn.jiguang.imui.chatinput.ChatInputView.onClick(ChatInputView.java:644)
        at android.view.View.performClick(View.java:6205)
        at android.view.View$PerformClick.run(View.java:23653)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1534)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1424)`

**Comment by dogbutcat** [comment]
是不是请求权限之后只出现空白界面然后拍照就崩溃了？

我试了应该是请求权限同时走了下方的初始化，而授权完后已经初始化完了，导致实际拍照对象为null，可惜我暂时不会改UI组件下的requestPermission😂
https://github.com/jpush/aurora-imui/blob/913da5bc2c11e9953ca03fdba17c9d7906e49477/ReactNative/android/src/main/java/cn/jiguang/imui/messagelist/viewmanager/ReactChatInputManager.java#L334-L368

**Comment by JoshLipan** [comment]
更新版本到0.10.11，未获取权限下不展现CameraUI
