### ISSUE TITLE
在android ChatInputView中，点击选择照片按钮时，出现java.lang.NoSuchMethodError: No virtual method load

### ISSUE THREAD

**Issue by 15050050972** [jpush/aurora-imui#439]
android min-sdk 21, target-sdk 27
点击选择照片，出现NoSuchMethodError，好像是和Glide有关。我删除了gradle中对glide的依赖，仍然报这个错。具体报错如下：
```
java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/cn.tianyu_studio.musicpartnerapp-bHEdjD7yNIQRR_HIZp4aqg==/split_lib_dependencies_apk.apk)
        at cn.jiguang.imui.chatinput.photo.PhotoAdapter.onBindViewHolder(PhotoAdapter.java:81)
        at cn.jiguang.imui.chatinput.photo.PhotoAdapter.onBindViewHolder(PhotoAdapter.java:33)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:19715)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19715)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19715)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19715)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19715)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1780)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1546)
        at android.view.View.layout(View.java:19715)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19715)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19715)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19715)
08-29 14:28:20.884 12589-12589/cn.tianyu_studio.musicpartnerapp E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19715)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19715)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:764)
        at android.view.View.layout(View.java:19715)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2544)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2260)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1440)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6857)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:968)
        at android.view.Choreographer.doCallbacks(Choreographer.java:780)
        at android.view.Choreographer.doFrame(Choreographer.java:715)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6618)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822)


```

**Comment by JoshLipan** [comment]
参考下#420

**Comment by 15050050972** [comment]
按照420楼的做法试了下。还是不行
试了以下5种方法

1:
```
implementation ('cn.jiguang.imui:chatinput:0.7.3') {
        exclude group: 'com.github.bumptech.glide', module: 'glide'
    }
implementation 'com.github.bumptech.glide:glide:4.7.1'
```
2:
```
implementation ('cn.jiguang.imui:chatinput:0.7.3') {
        exclude group: 'com.github.bumptech.glide', module: 'glide'
    }
implementation 'com.github.bumptech.glide:glide:3.8.0'
```
3:
```
implementation ('cn.jiguang.imui:chatinput:0.7.3') 
implementation 'com.github.bumptech.glide:glide:3.8.0'
```
4:
```
implementation ('cn.jiguang.imui:chatinput:0.7.3') 
implementation 'com.github.bumptech.glide:glide:4.7.1'
```
5:
```
implementation ('cn.jiguang.imui:chatinput:0.7.3') 
```

这是什么原因？另外我在项目中实际实用的是另一种图片框架，项目中并没有依赖glide

**Comment by JoshLipan** [comment]
参考[sample](https://github.com/jpush/aurora-imui/tree/master/Android/sample)试下，官方sample用的glide版本是4.6.1
