### ISSUE TITLE
window上运行android 报错

### ISSUE THREAD

**Issue by 25juan** [jpush/aurora-imui#456]
下载最新的sample，在Windows上面运行Android报错。还有就是你们sample在android 文件夹下少提交了`gradlew.bat`文件，导致在windows 上面不能正常运行。

![image](https://user-images.githubusercontent.com/14308183/45463858-6c71fe00-b740-11e8-8bd4-c2d57f97cb92.png)

**Comment by JoshLipan** [comment]
升级sample下IMUI插件版本到0.11.0

**Comment by 25juan** [comment]
华为荣耀6x ,android 版本7.0 点击拍照的时候直接crash 了

**Comment by JoshLipan** [comment]
将插件对应位置[mChatInput.dismissMenuLayout();](https://github.com/jpush/aurora-imui/blob/master/ReactNative/android/src/main/java/cn/jiguang/imui/messagelist/viewmanager/ReactChatInputManager.java#L433) 改成
```Java
mContext.runOnUiQueueThread(new Runnable() {
                    @Override
                    public void run() {
                        mChatInput.dismissMenuLayout();
                    }
                });
```
看下是否能解决crash问题

**Comment by 25juan** [comment]
全屏模式下进行拍照闪退，as logcat日志为：

```
7171-17884/com.testrnimuiexample E/AndroidRuntime: FATAL EXCEPTION: Camera Background
                                                                       Process: com.testrnimuiexample, PID: 17171
                                                                       java.lang.IllegalStateException: CameraDevice was already closed
                                                                           at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2184)
                                                                           at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureRequest(CameraDeviceImpl.java:692)
                                                                           at cn.jiguang.imui.chatinput.camera.CameraNew.captureStillPicture(CameraNew.java:715)
                                                                           at cn.jiguang.imui.chatinput.camera.CameraNew.access$200(CameraNew.java:66)
                                                                           at cn.jiguang.imui.chatinput.camera.CameraNew$2.process(CameraNew.java:225)
                                                                           at cn.jiguang.imui.chatinput.camera.CameraNew$2.onCaptureCompleted(CameraNew.java:269)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
                                                                           at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
                                                                           at android.os.Handler.handleCallback(Handler.java:808)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                           at android.os.Looper.loop(Looper.java:166)
                                                                           at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by JoshLipan** [comment]
是必现的问题吗，我这边测试还没遇到这个问题

**Comment by 25juan** [comment]
是的，我这边运行这个demo 有些卡，所以在全屏模式下我点击照相按钮会连续多点几次，然后就直接crash 了。

**Comment by 25juan** [comment]
是的，我这边运行这个demo 有些卡，所以在全屏模式下我点击照相按钮会连续多点几次，然后就直接crash 了。

**Comment by JoshLipan** [comment]
更新最新版本v0.11.1
