### ISSUE TITLE
拍照/录像最大化后点击最小化闪退

### ISSUE THREAD

**Issue by laienliang** [jpush/aurora-imui#507]
### My environment:

拍照/录像时，先最大后，然后点击最小化功能，安卓直接闪退，错误如下：
```
E/AndroidRuntime: FATAL EXCEPTION: Camera Background
                  Process: com.gy_oa_app, PID: 12902
                  java.lang.IllegalStateException: CameraDevice was already closed
                      at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:1986)
                      at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:857)
                      at android.hardware.camera2.impl.CameraDeviceImpl.setRepeatingRequest(CameraDeviceImpl.java:904)
                      at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:236)
                      at cn.jiguang.imui.chatinput.camera.CameraNew.updatePreview(CameraNew.java:474)
                      at cn.jiguang.imui.chatinput.camera.CameraNew.access$900(CameraNew.java:66)
                      at cn.jiguang.imui.chatinput.camera.CameraNew$4.onConfigured(CameraNew.java:393)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
                      at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by JoshLipan** [comment]
录像途中点击最小化报的错吗

**Comment by laienliang** [comment]
> 录像途中点击最小化报的错吗

不是录像途中，是点击最小化就会报错，点击录像完成也会闪退

**Comment by JoshLipan** [comment]
参照 #514
