### ISSUE TITLE
android 5.1.1 拍照闪退 但是重新打开张图片显示已发出去

### ISSUE THREAD

**Issue by JohnTree** [jpush/aurora-imui#530]
E/AndroidRuntime: FATAL EXCEPTION: Camera Background
                                                 
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.camera2.CameraCaptureSession.capture(android.hardware.camera2.CaptureRequest, android.hardware.camera2.CameraCaptureSession$CaptureCallback, android.os.Handler)' on a null object reference
                                                       at cn.jiguang.imui.chatinput.camera.CameraNew.unlockFocus(CameraNew.java:761)
                                                       at cn.jiguang.imui.chatinput.camera.CameraNew.access$1100(CameraNew.java:66)
                                                       at cn.jiguang.imui.chatinput.camera.CameraNew$6.onCaptureCompleted(CameraNew.java:740)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
                                                       at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:159)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by cnpmge** [comment]
请问如何解决的？
