### ISSUE TITLE
使用Android messageList出现imui布局空指针

### ISSUE THREAD

**Issue by ray26** [jpush/aurora-imui#569]
### My environment:
- native version:9.0
- messageList version:0.8.0

Logcat:
```
romerxzh
穿过空的声音
18小时前
2019-02-22 19:46:12.188 15999-15999/cn.edu.uestc.meet_on_the_road_of_uestc E/CrashReport: java.lang.NullPointerException: Attempt to read from field 'int cn.jiguang.imui.messages.MsgListAdapter$HoldersConfig.mSendTxtLayout' on a null object reference
        at cn.jiguang.imui.messages.MsgListAdapter$HoldersConfig.access$000(MsgListAdapter.java:689)
        at cn.jiguang.imui.messages.MsgListAdapter.onCreateViewHolder(MsgListAdapter.java:129)
        at cn.jiguang.imui.messages.MsgListAdapter.onCreateViewHolder(MsgListAdapter.java:26)
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6685)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:20964)
        at android.view.ViewGroup.layout(ViewGroup.java:6276)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
        at android.view.View.layout(View.java:20964)
        at android.view.ViewGroup.layout(ViewGroup.java:6276)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20964)
        at android.view.ViewGroup.layout(ViewGroup.java:6276)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
        at android.view.View.layout(View.java:20964)
        at android.view.ViewGroup.layout(ViewGroup.java:6276)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20964)
        at android.view.ViewGroup.layout(ViewGroup.java:6276)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
        at android.view.View.layout(View.java:20964)
        at android.view.ViewGroup.layout(ViewGroup.java:6276)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:880)
        at android.view.View.layout(View.java:20964)
        at android.view.ViewGroup.layout(ViewGroup.java:6276)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3024)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2532)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1624)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7926)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1079)
        at android.view.Choreographer.doCallbacks(Choreographer.java:885)
        at android.view.Choreographer.doFrame(Choreographer.java:809)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1065)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
    	at java.lang.reflect.Method.in
```
9.0启动界面时，出现自带布局空指针

**Comment by JoshLipan** [comment]
自定义布局吗

**Comment by ray26** [comment]
不是自定义布局，是直接引用的messagelist

**Comment by JoshLipan** [comment]
你用的哪个版本的 messageList，官方 demo 测试下看有没有问题

**Comment by ray26** [comment]
官方demo测试没有问题，我用的是0.8.0的messagelist

**Comment by JoshLipan** [comment]
如果想使用 imui 自带的布局，需要初始化 adapter 的时候传入 [MsgListAdapter.HoldersConfig](https://github.com/jpush/aurora-imui/blob/master/Android/sample/exampleui/src/main/java/imui/jiguang/cn/imuisample/messages/MessageListActivity.java#L548)

**Comment by ray26** [comment]
如果没有自定义holder也要传吗

**Comment by ray26** [comment]
ok,我看到了，蟹蟹
