### ISSUE TITLE
Android9.0获取MessageStatus标识符空指针

### ISSUE THREAD

**Issue by ray26** [jpush/aurora-imui#570]
- Android 9.0
- MessageList 0.8.0

```2019-02-25 12:25:44.933 30837-30837/cn.edu.uestc.meet_on_the_road_of_uestc E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.edu.uestc.meet_on_the_road_of_uestc, PID: 30837
    java.lang.NullPointerException: Attempt to invoke virtual method 'int cn.jiguang.imui.commons.models.IMessage$MessageStatus.ordinal()' on a null object reference
        at cn.jiguang.imui.messages.TxtViewHolder.onBind(TxtViewHolder.java:64)
        at cn.jiguang.imui.messages.TxtViewHolder.onBind(TxtViewHolder.java:17)
        at cn.jiguang.imui.messages.MsgListAdapter.onBindViewHolder(MsgListAdapter.java:260)
        at cn.jiguang.imui.messages.MsgListAdapter.onBindViewHolder(MsgListAdapter.java:26)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:20964)
        at android.view.ViewGroup.layout(ViewGroup.java:6276)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
        at android.view.View.layout(View.java:20964)
        at android.view.ViewGroup.layout(ViewGroup.java:6276)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20964)
        at android.view.ViewGroup.layout(ViewGroup.java:6276)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
        at android.view.View.layout(View.java:20964)
        at android.view.ViewGroup.layout(ViewGroup.java:6276)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20964)
        at android.view.ViewGroup.layout(ViewGroup.java:6276)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
        at android.view.View.layout(View.java:20964)
        at android.view.ViewGroup.layout(ViewGroup.java:6276)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:880)
        at android.view.View.layout(View.java:20964)
        at android.view.ViewGroup.layout(ViewGroup.java:6276)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3024)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2532)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1624)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7926)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1079)
        at android.view.Choreographer.doCallbacks(Choreographer.java:885)
2019-02-25 12:25:44.934 30837-30837/cn.edu.uestc.meet_on_the_road_of_uestc E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:809)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1065)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)```
又是诡异的空指针

**Comment by JoshLipan** [comment]
发消息报的错？没传[消息状态](https://github.com/jpush/aurora-imui/blob/master/Android/messagelist/src/main/java/cn/jiguang/imui/commons/models/IMessage.java#L65)吧，建议你参考 demo 调用。
还有报 issue 能否提供前因后果，以及自己对应 issue 做了什么操作，单贴一个异常 log 上来难提供支持

**Comment by ray26** [comment]
好的，蟹蟹
