### ISSUE TITLE
aurora-imui-react-native for react-native 0.66 error

### ISSUE THREAD

**Issue by ng520tx** [jpush/aurora-imui#707]
### My environment:

> Configure project :react-native-picker
WARNING:: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed in version 7.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
WARNING:: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported 
version (30.0.2) for Android Gradle Plugin 4.2.2.
Android SDK Build Tools 30.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the 
Android Gradle Plugin now has a default version of the build tools.

> Task :app:checkDebugAarMetadata FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
20 actionable tasks: 2 executed, 18 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for cn.jiguang.imui:messagelist:+ as no versions of cn.jiguang.imui:messagelist are available.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/cn/jiguang/imui/messagelist/maven-metadata.xml
       - file:/C:/Users/prince/.m2/repository/cn/jiguang/imui/messagelist/
       - file:/D:/new_react_native_project/second_app/node_modules/react-native/android/cn/jiguang/imui/messagelist/maven-metadata.xml
       - file:/D:/new_react_native_project/second_app/node_modules/jsc-android/dist/cn/jiguang/imui/messagelist/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/cn/jiguang/imui/messagelist/maven-metadata.xml
       - https://www.jitpack.io/cn/jiguang/imui/messagelist/maven-metadata.xml
     Required by:
         project :app > project :aurora-imui-react-native
   > Could not find any matches for cn.jiguang.imui:chatinput:+ as no versions of cn.jiguang.imui:chatinput are available.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/cn/jiguang/imui/chatinput/maven-metadata.xml
       - file:/C:/Users/prince/.m2/repository/cn/jiguang/imui/chatinput/
       - file:/D:/new_react_native_project/second_app/node_modules/react-native/android/cn/jiguang/imui/chatinput/maven-metadata.xml
       - file:/D:/new_react_native_project/second_app/node_modules/jsc-android/dist/cn/jiguang/imui/chatinput/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/cn/jiguang/imui/chatinput/maven-metadata.xml
       - https://www.jitpack.io/cn/jiguang/imui/chatinput/maven-metadata.xml
     Required by:
         project :app > project :aurora-imui-react-native
   > Could not find pub.devrel:easypermissions:1.0.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/pub/devrel/easypermissions/1.0.1/easypermissions-1.0.1.pom
       - file:/C:/Users/prince/.m2/repository/pub/devrel/easypermissions/1.0.1/easypermissions-1.0.1.pom
       - file:/D:/new_react_native_project/second_app/node_modules/react-native/android/pub/devrel/easypermissions/1.0.1/easypermissions-1.0.1.pom
       - file:/D:/new_react_native_project/second_app/node_modules/jsc-android/dist/pub/devrel/easypermissions/1.0.1/easypermissions-1.0.1.pom
       - https://dl.google.com/dl/android/maven2/pub/devrel/easypermissions/1.0.1/easypermissions-1.0.1.pom       
       - https://www.jitpack.io/pub/devrel/easypermissions/1.0.1/easypermissions-1.0.1.pom
     Required by:
         project :app > project :aurora-imui-react-native

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for cn.jiguang.imui:messagelist:+ as no versions of cn.jiguang.imui:messagelist are available.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/cn/jiguang/imui/messagelist/maven-metadata.xml
       - file:/C:/Users/prince/.m2/repository/cn/jiguang/imui/messagelist/
       - file:/D:/new_react_native_project/second_app/node_modules/react-native/android/cn/jiguang/imui/messagelist/maven-metadata.xml
       - file:/D:/new_react_native_project/second_app/node_modules/jsc-android/dist/cn/jiguang/imui/messagelist/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/cn/jiguang/imui/messagelist/maven-metadata.xml
       - https://www.jitpack.io/cn/jiguang/imui/messagelist/maven-metadata.xml
     Required by:
         project :app > project :aurora-imui-react-native
   > Could not find any matches for cn.jiguang.imui:chatinput:+ as no versions of cn.jiguang.imui:chatinput are available.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/cn/jiguang/imui/chatinput/maven-metadata.xml
       - file:/C:/Users/prince/.m2/repository/cn/jiguang/imui/chatinput/
       - file:/D:/new_react_native_project/second_app/node_modules/react-native/android/cn/jiguang/imui/chatinput/maven-metadata.xml
       - file:/D:/new_react_native_project/second_app/node_modules/jsc-android/dist/cn/jiguang/imui/chatinput/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/cn/jiguang/imui/chatinput/maven-metadata.xml
       - https://www.jitpack.io/cn/jiguang/imui/chatinput/maven-metadata.xml
     Required by:
         project :app > project :aurora-imui-react-native
   > Could not find pub.devrel:easypermissions:1.0.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/pub/devrel/easypermissions/1.0.1/easypermissions-1.0.1.pom
       - file:/C:/Users/prince/.m2/repository/pub/devrel/easypermissions/1.0.1/easypermissions-1.0.1.pom
       - file:/D:/new_react_native_project/second_app/node_modules/react-native/android/pub/devrel/easypermissions/1.0.1/easypermissions-1.0.1.pom
       - file:/D:/new_react_native_project/second_app/node_modules/jsc-android/dist/pub/devrel/easypermissions/1.0.1/easypermissions-1.0.1.pom
       - https://dl.google.com/dl/android/maven2/pub/devrel/easypermissions/1.0.1/easypermissions-1.0.1.pom       
       - https://www.jitpack.io/pub/devrel/easypermissions/1.0.1/easypermissions-1.0.1.pom
     Required by:
         project :app > project :aurora-imui-react-native

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s

    at makeError (D:\new_react_native_project\second_app\node_modules\execa\index.js:174:9)
    at D:\new_react_native_project\second_app\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (D:\new_react_native_project\second_app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (D:\new_react_native_project\second_app\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.

**Comment by chengliu0508** [comment]
i have the same problem
