### ISSUE TITLE
相机崩溃

### ISSUE THREAD

**Issue by lulululbj** [jpush/aurora-imui#80]
Nexus 6p  API23 相机进入全屏时崩溃，错误信息如下：
`
java.lang.SecurityException: Lacking privileges to access camera service
at 
android.hardware.camera2.utils.CameraBinderDecorator.throwOnError(CameraBinderDecorator.java:108)
at android.hardware.camera2.utils.CameraBinderDecorator$CameraBinderDecoratorListener.onAfterInvocation(CameraBinderDecorator.java:73)
at android.hardware.camera2.utils.Decorator.invoke(Decorator.java:81)
at java.lang.reflect.Proxy.invoke(Proxy.java:393)
at $Proxy2.cancelRequest(Unknown Source)
at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:926)
at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:378)
at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:514)
at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:228)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7229)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
`

**Comment by KenChoi1992** [comment]
@lulululbj 有没有拿到 camera2 相机权限

**Comment by lulululbj** [comment]
@KenChoi1992 进入聊天界面点击相机按钮小屏幕状态下时正常的 点击全屏按钮就崩溃了

**Comment by KenChoi1992** [comment]
@lulululbj 试试新版本
